controller_manager:
  ros__parameters:
    update_rate: 125

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController
    
    state_controller:
      type: ethercat_controllers/CiA402Controller

velocity_controller:
  ros__parameters:
    joints:
      - wheel_right_joint
      - wheel_left_joint

position_controller:
  ros__parameters:
    joints:
      - wheel_right_joint
      - wheel_left_joint

joint_state_broadcaster:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint
    # interfaces:
    #   - position
    #   - velocity


diff_drive_controller:
  ros__parameters:
    use_sim_time: false
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_separation: 0.288
    wheel_radius: 0.033

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

state_controller:
  ros__parameters:
    dofs:
      - wheel_right_joint
