# Configuration file for Beckhoff EL7211
vendor_id: 0x00000002            # Beckhoff
product_id: 0x1C2B3052           # from ProductCode=472592466
assign_activate: 0x700  # DC Synch register
auto_fault_reset: true

# count a giro encoder:
# 1048576 counts/rev  
# ethercat upload 0x9010 0x15 --type uint32 -p 1

sdo:
  - {index: 0x8010, sub_index: 0x0031, type: uint32, value: 5000}  # Velocity limitation [rpm] - max sw velocity
  - {index: 0x8011, sub_index: 0x001B, type: uint32, value: 12000}  # DRV Motor Settings / Motor speed limitation [rpm] - max motor velocity
  - {index: 0x8010, sub_index: 0x0019, type: uint32, value: 48000}  # Nominal DC link voltage

tpdo:  # TxPDO
  - index: 0x1A00
    channels:
      - {index: 0x6000, sub_index: 0x11, type: uint32, state_interface: position, factor: 0.00000598907}
  - index: 0x1A01
    channels:
      - {index: 0x6010, sub_index: 0x01, type: uint16, state_interface: status_word}
  - index: 0x1A02
    channels:
      - {index: 0x6010, sub_index: 0x07, type: int32, state_interface: velocity, factor: 0.0000233948}
  - index: 0x1A0E
    channels:
      - {index: 0x6010, sub_index: 0x03, type: uint8, state_interface: mode_of_operation}

  # - index: 0x1a03
  #   channels:
  #     - {index: 0x6010, sub_index: 8, type: int16, state_interface: effort, factor: 0.001}
  # - index: 0x1a04
  #   channels:
  #     - {index: 0x6010, sub_index: 18, type: uint16, state_interface: info_data_1}
  # - index: 0x1a05
  #   channels:
  #     - {index: 0x6010, sub_index: 19, type: uint16, state_interface: info_data_2}
  # - index: 0x1a06
  #   channels:
  #     - {index: 0x6010, sub_index: 6, type: int32, state_interface: following_error}


rpdo:
  - index: 0x1600
    channels:
      - {index: 0x7010, sub_index: 0x01, type: uint16, command_interface: control_word}

  - index: 0x1601
    channels:
      - {index: 0x7010, sub_index: 0x06, type: int32, command_interface: velocity, factor: 42744.42675} 



  # - index: 0x1602
  #   channels:
  #     - {index: 0x7010, sub_index: 9, type: int16, command_interface: effort, factor: 1000.0}

  # - index: 0x1603
  #   channels:
  #     - {index: 0x7010, sub_index: 14, type: uint16, command_interface: commutation_angle}

  # - index: 0x1604
  #   name: drv_torque_limitation
  #   channels:
  #     - {index: 0x7010, sub_index: 11, type: uint16, command_interface: torque_limit}

  # - index: 0x1605ex: 3, type: uint8, command_interface: mode_of_operation, default: 9}

  #   name: drv_torque_offset
  #   channels:
  #     - {index: 0x7010, sub_index: 10, type: int16, command_interface: torque_offset}

  - index: 0x1606
    channels:
      - {index: 0x7010, sub_index: 0x05, type: uint32, command_interface: position, factor: 166970.700637}

  - index: 0x1608
    channels:
      - {index: 0x7010, sub_index: 3, type: uint8, command_interface: mode_of_operation, default: 9}

# Sync Manager
sm:
  - {index: 0, type: output, pdo: ~, watchdog: disable}  # SM0: Mailbox
  - {index: 1, type: input,  pdo: ~, watchdog: disable}  # SM1: unused input
  - {index: 2, type: output, pdo: rpdo, watchdog: enable} # SM2: RPDO
  - {index: 3, type: input,  pdo: tpdo, watchdog: enable} # SM3: TPDO
